// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WarehouseEngine.Domain.Entities;

[Index("PositionId", Name = "IX_Employee01")]
[Index("SupervisorEmployeeId", Name = "IX_Employee02")]
public partial class Employee
{
    [Key]
    public required Guid Id { get; set; }

    [StringLength(30)]
    public required string FirstName { get; set; }

    [StringLength(30)]
    public string? MiddleName { get; set; }

    [StringLength(30)]
    public required string LastName { get; set; }

    [StringLength(32)]
    public required string UserName { get; set; }

    public Guid PositionId { get; set; }

    public Guid SupervisorEmployeeId { get; set; }

    [MaxLength(32)]
    public byte[]? SocialSecurityNumberHash { get; set; }

    [StringLength(4)]
    public string? SocialSecuritySerialNumber { get; set; }

    [ForeignKey("PositionId")]
    [InverseProperty("Employee")]
    public virtual Position? Position { get; set; }

    [ForeignKey("SupervisorEmployeeId")]
    [InverseProperty("InverseSupervisorEmployee")]
    public virtual required Employee SupervisorEmployee { get; set; }
    [InverseProperty("SupervisorEmployee")]
    public virtual ICollection<Employee> InverseSupervisorEmployee { get; init; } = new List<Employee>();
    [InverseProperty("AssignedToEmployee")]
    public virtual ICollection<WarehousePickList> WarehousePickListAssignedToEmployee { get; set; } = new List<WarehousePickList>();

    [InverseProperty("CreatedByEmployee")]
    public virtual ICollection<WarehousePickList> WarehousePickListCreatedByEmployee { get; set; } = new List<WarehousePickList>();
}
