// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WarehouseEngine.Domain.Entities;

[PrimaryKey("OrderId", "WarehouseItemId")]
[Index("OrderId", Name = "IX_OrderWarehouseItem01")]
[Index("WarehouseItemId", Name = "IX_OrderWarehouseItem02")]
public partial class OrderWarehouseItem
{
    [Key]
    public Guid OrderId { get; set; }

    [Key]
    public Guid WarehouseItemId { get; set; }

    public int Quantity { get; set; }

    [ForeignKey("OrderId")]
    [InverseProperty("OrderWarehouseItem")]
    public virtual Order? Order { get; set; }

    [ForeignKey("WarehouseItemId")]
    [InverseProperty("OrderWarehouseItem")]
    public virtual WarehouseItem? WarehouseItem { get; set; }

    [InverseProperty("OrderWarehouseItem")]
    public virtual ICollection<WarehousePickListItem> WarehousePickListItem { get; set; } = new List<WarehousePickListItem>();
}
