// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WarehouseEngine.Domain.Entities;

[PrimaryKey("VendorId", "ItemId")]
[Index("VendorId", Name = "IX_VendorItem01")]
[Index("ItemId", Name = "IX_VendorItem02")]
public partial class VendorItem
{
    [Key]
    public Guid VendorId { get; set; }

    [Key]
    public Guid ItemId { get; set; }

    public DateTime DateCreated { get; set; }

    [StringLength(80)]
    public string CreatedBy { get; set; } = null!;

    public DateTime? DateModified { get; set; }

    [StringLength(80)]
    public string? ModifiedBy { get; set; }

    [ForeignKey("ItemId")]
    [InverseProperty("VendorItem")]
    public virtual Item Item { get; set; } = null!;

    [ForeignKey("VendorId")]
    [InverseProperty("VendorItem")]
    public virtual Vendor Vendor { get; set; } = null!;
}