// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WarehouseEngine.Domain.Entities;

public partial class Warehouse
{
    [Key]
    public required Guid Id { get; set; }

    [StringLength(32)]
    public required string Name { get; set; }

    [InverseProperty("Warehouse")]
    public virtual ICollection<WarehouseItem> WarehouseItem { get; init; } = new List<WarehouseItem>();

    [InverseProperty("Warehouse")]
    public virtual ICollection<WarehousePickList> WarehousePickList { get; init; } = new List<WarehousePickList>();
}
