// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WarehouseEngine.Domain.Entities;

[Index("WarehouseId", Name = "IX_WarehouseItem01")]
[Index("ItemId", Name = "IX_WarehouseItem02")]
public partial class WarehouseItem
{
    [Key]
    public required Guid Id { get; set; }

    public required Guid WarehouseId { get; set; }

    public required Guid ItemId { get; set; }

    public int Quantity { get; set; }

    [Column(TypeName = "decimal(15, 3)")]
    public decimal? Price { get; set; }

    public DateTime DateCreated { get; set; }

    [StringLength(80)]
    public string CreatedBy { get; set; } = null!;

    public DateTime? DateModified { get; set; }

    [StringLength(80)]
    public string? ModifiedBy { get; set; }

    [ForeignKey("ItemId")]
    [InverseProperty("WarehouseItem")]
    public virtual Item? Item { get; set; }

    [ForeignKey("WarehouseId")]
    [InverseProperty("WarehouseItem")]
    public virtual Warehouse? Warehouse { get; set; }

    [InverseProperty("WarehouseItem")]
    public virtual ICollection<OrderWarehouseItem> OrderWarehouseItem { get; init; } = new List<OrderWarehouseItem>();

    [InverseProperty("WarehouseItem")]
    public virtual ICollection<OrderWarehouseItemOutOfStock> OrderWarehouseItemOutOfStock { get; init; } = new List<OrderWarehouseItemOutOfStock>();

    [InverseProperty("WarehouseItem")]
    public virtual ICollection<PurchaseOrderWarehouseItem> PurchaseOrderWarehouseItem { get; init; } = new List<PurchaseOrderWarehouseItem>();

    [InverseProperty("WarehouseItem")]
    public virtual ICollection<WarehousePickListItem> WarehousePickListItem { get; init; } = new List<WarehousePickListItem>();
}
