// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WarehouseEngine.Domain.Entities;

[Index("AssignedToEmployeeId", Name = "IX_WarehousePickList_AssignedToEmployeeId")]
[Index("OrderId", Name = "IX_WarehousePickList_OrderId")]
[Index("Status", Name = "IX_WarehousePickList_Status")]
[Index("WarehouseId", Name = "IX_WarehousePickList_WarehouseId")]
public partial class WarehousePickList
{
    [Key]
    public Guid Id { get; set; }

    public Guid OrderId { get; set; }

    public Guid WarehouseId { get; set; }

    [StringLength(25)]
    public string PickListNumber { get; set; } = null!;

    public byte Status { get; set; }

    public DateTime CreatedDate { get; set; }

    public Guid CreatedByEmployeeId { get; set; }

    public Guid? AssignedToEmployeeId { get; set; }

    public DateTime? StartedDate { get; set; }

    public DateTime? CompletedDate { get; set; }

    public byte Priority { get; set; }

    [StringLength(500)]
    public string? Notes { get; set; }

    [ForeignKey("AssignedToEmployeeId")]
    [InverseProperty("WarehousePickListAssignedToEmployee")]
    public virtual Employee? AssignedToEmployee { get; set; }

    [ForeignKey("CreatedByEmployeeId")]
    [InverseProperty("WarehousePickListCreatedByEmployee")]
    public virtual Employee CreatedByEmployee { get; set; } = null!;

    [ForeignKey("OrderId")]
    [InverseProperty("WarehousePickList")]
    public virtual Order Order { get; set; } = null!;

    [ForeignKey("WarehouseId")]
    [InverseProperty("WarehousePickList")]
    public virtual Warehouse Warehouse { get; set; } = null!;

    [InverseProperty("PickList")]
    public virtual ICollection<WarehousePickListItem> WarehousePickListItem { get; set; } = new List<WarehousePickListItem>();
}