// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WarehouseEngine.Domain.Entities;

[PrimaryKey("PickListId", "WarehouseItemId")]
[Index("Status", Name = "IX_WarehousePickListItem_Status")]
[Index("WarehouseItemId", Name = "IX_WarehousePickListItem_WarehouseItemId")]
public partial class WarehousePickListItem
{
    [Key]
    public Guid PickListId { get; set; }

    [Key]
    public Guid WarehouseItemId { get; set; }

    public Guid OrderId { get; set; }

    public int QuantityToPick { get; set; }

    public int QuantityPicked { get; set; }

    [StringLength(50)]
    public string? BinLocation { get; set; }

    public int PickSequence { get; set; }

    public byte Status { get; set; }

    [StringLength(255)]
    public string? Notes { get; set; }

    [ForeignKey("OrderId, WarehouseItemId")]
    [InverseProperty("WarehousePickListItem")]
    public virtual OrderWarehouseItem OrderWarehouseItem { get; set; } = null!;

    [ForeignKey("PickListId")]
    [InverseProperty("WarehousePickListItem")]
    public virtual WarehousePickList PickList { get; set; } = null!;

    [ForeignKey("WarehouseItemId")]
    [InverseProperty("WarehousePickListItem")]
    public virtual WarehouseItem WarehouseItem { get; set; } = null!;
}